name: sentinel

services:
  sentinel-api:
    build:
      context: .
      dockerfile: src/Sentinel.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - "5156:8080"
    depends_on:
      - otel-collector

  incidentlab-order-api:
    build:
      context: .
      dockerfile: samples/IncidentLab.OrderApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - "5112:8080"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.157.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./deploy/otel/collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    restart: unless-stopped
