// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sentinel.Infrastructure.Persistence;

#nullable disable

namespace Sentinel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    [Migration("20260810161621_AddAlertIngestionInbox")]
    partial class AddAlertIngestionInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sentinel.Domain.Evidence.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.Property<string>("SourceService")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_service");

                    b.Property<string>("SourceSpanId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_span_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_trace_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verification_status");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_evidence_incident_content_hash");

                    b.HasIndex("IncidentId", "ObservedAt")
                        .HasDatabaseName("ix_evidence_incident_observed_at");

                    b.HasIndex("IncidentId", "SourceTraceId")
                        .HasDatabaseName("ix_evidence_incident_source_trace_id");

                    b.HasIndex("SourceTraceId", "SourceSpanId")
                        .HasDatabaseName("ix_evidence_source_trace_span");

                    b.HasIndex("IncidentId", "SourceTraceId", "SourceSpanId")
                        .IsUnique()
                        .HasDatabaseName("ux_evidence_incident_source_trace_span")
                        .HasFilter("\"type\" = 'Trace' AND \"source_system\" = 'Tempo'");

                    b.ToTable("evidence", (string)null);
                });

            modelBuilder.Entity("Sentinel.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_incidents_created_at");

                    b.HasIndex("Service", "Status")
                        .HasDatabaseName("ix_incidents_service_status");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Sentinel.Domain.Ingestion.AlertOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alert_name");

                    b.Property<string>("AnnotationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("annotations");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment");

                    b.Property<string>("GeneratorUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("generator_url");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<string>("OccurrenceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("occurrence_key");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceKey")
                        .IsUnique()
                        .HasDatabaseName("ux_alert_occurrences_occurrence_key");

                    b.HasIndex("Service", "StartedAt")
                        .HasDatabaseName("ix_alert_occurrences_service_started_at");

                    b.ToTable("alert_occurrences", (string)null);
                });

            modelBuilder.Entity("Sentinel.Domain.Ingestion.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_occurrence_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_code");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AlertOccurrenceId")
                        .IsUnique()
                        .HasDatabaseName("ux_ingestion_runs_alert_occurrence_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_ingestion_runs_status_created_at");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("Sentinel.Domain.Investigations.EvidenceRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("explanation");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("InvestigationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigation_run_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<Guid>("SourceEvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_evidence_id");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("strength");

                    b.Property<Guid>("TargetEvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_evidence_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("InvestigationRunId")
                        .HasDatabaseName("ix_evidence_relationships_investigation_run_id");

                    b.HasIndex("SourceEvidenceId");

                    b.HasIndex("TargetEvidenceId");

                    b.ToTable("evidence_relationships", (string)null);
                });

            modelBuilder.Entity("Sentinel.Domain.Investigations.Hypothesis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("InvestigationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigation_run_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("reasoning");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("scope");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("statement");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("InvestigationRunId")
                        .HasDatabaseName("ix_hypotheses_investigation_run_id");

                    b.ToTable("hypotheses", (string)null);
                });

            modelBuilder.Entity("Sentinel.Domain.Investigations.InvestigationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("ConsideredEvidenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("considered_evidence_count");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalEvidenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_evidence_count");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "StartedAt")
                        .HasDatabaseName("ix_investigation_runs_incident_started_at");

                    b.ToTable("investigation_runs", (string)null);
                });

            modelBuilder.Entity("Sentinel.Domain.Evidence.EvidenceItem", b =>
                {
                    b.HasOne("Sentinel.Domain.Incidents.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sentinel.Domain.Ingestion.IngestionRun", b =>
                {
                    b.HasOne("Sentinel.Domain.Ingestion.AlertOccurrence", null)
                        .WithOne()
                        .HasForeignKey("Sentinel.Domain.Ingestion.IngestionRun", "AlertOccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sentinel.Domain.Investigations.EvidenceRelationship", b =>
                {
                    b.HasOne("Sentinel.Domain.Incidents.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentinel.Domain.Investigations.InvestigationRun", null)
                        .WithMany()
                        .HasForeignKey("InvestigationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentinel.Domain.Evidence.EvidenceItem", null)
                        .WithMany()
                        .HasForeignKey("SourceEvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sentinel.Domain.Evidence.EvidenceItem", null)
                        .WithMany()
                        .HasForeignKey("TargetEvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sentinel.Domain.Investigations.Hypothesis", b =>
                {
                    b.HasOne("Sentinel.Domain.Incidents.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentinel.Domain.Investigations.InvestigationRun", null)
                        .WithMany()
                        .HasForeignKey("InvestigationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Sentinel.Domain.Investigations.HypothesisEvidenceReference", "EvidenceReferences", b1 =>
                        {
                            b1.Property<Guid>("hypothesis_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EvidenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("evidence_id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("role");

                            b1.HasKey("hypothesis_id", "EvidenceId");

                            b1.HasIndex("EvidenceId");

                            b1.ToTable("hypothesis_evidence_references", (string)null);

                            b1.HasOne("Sentinel.Domain.Evidence.EvidenceItem", null)
                                .WithMany()
                                .HasForeignKey("EvidenceId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("hypothesis_id");
                        });

                    b.Navigation("EvidenceReferences");
                });

            modelBuilder.Entity("Sentinel.Domain.Investigations.InvestigationRun", b =>
                {
                    b.HasOne("Sentinel.Domain.Incidents.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
